import {
  ReviewOptions,
  ReviewOutput,
  ReviewResult,
  PRAnalysis,
  ChangedFile,
} from "./types.js";
import { logger } from "../utils/logger.js";
import { PrivacyGuard } from "../security/privacy-guard.js";
import { ExcludeFilter } from "../security/exclude-filter.js";
import { SmartFilter } from "./smart-filter.js";
import { PRAnalyzer } from "./analyzer.js";
import { StrategySelector } from "./strategy-selector.js";
import { ConsensusEngine } from "./consensus-engine.js";
import { ClaudeAdapter } from "../adapters/claude-api.js";
import { GitHubAdapter } from "../adapters/github-api.js";
import { FrameworkDetector } from "../frameworks/detector.js";
import { ConfigLoader } from "../utils/config-loader.js";
import { ProjectRulesLoader } from "../false-positive/project-rules-loader.js";

/**
 * Convert model ID to display name
 * e.g. "claude-opus-4-6" → "Claude Opus 4.6"
 */
function formatModelName(modelId: string): string {
  const match = modelId.match(/^claude-(\w+)-(\d+)-(\d+)/);
  if (match) {
    const [, family, major, minor] = match;
    return `Claude ${family.charAt(0).toUpperCase() + family.slice(1)} ${major}.${minor}`;
  }
  return modelId;
}

/**
 * Extract consensus verdict/fpRate for display in metrics
 */
function extractConsensusData(result: ReviewResult): {
  verdict: string;
  fpRate: string;
} {
  let verdict = result.summary.verdict || "";
  const fpRate = result.summary.fpRate || "—";

  // Fallback inference if not provided
  if (!verdict) {
    if (result.summary.totalIssues === 0) verdict = "APPROVE";
    else verdict = "COMMENT";
  }

  return { verdict, fpRate };
}

/**
 * Format issues as a flat list (fallback when no debateNarrative)
 */
function formatFallbackIssues(result: ReviewResult): string {
  const lines: string[] = [];

  if (result.issues.length === 0) {
    lines.push("### Review");
    lines.push("");
    lines.push(result.summary.overallAssessment);
    return lines.join("\n");
  }

  lines.push("### Issues");
  lines.push("");

  for (const issue of result.issues) {
    const emoji = {
      security: "🔐",
      bug: "🐛",
      performance: "⚡",
      maintainability: "🔧",
    }[issue.type];

    lines.push(`#### ${emoji} ${issue.title}`);
    lines.push("");
    lines.push(
      `**File**: \`${issue.file}\`${issue.line ? ` (Line ${issue.line})` : ""}`
    );
    lines.push(`**Type**: ${issue.type} | **Confidence**: ${issue.confidence}`);
    lines.push("");
    lines.push(issue.description);

    if (issue.suggestion) {
      lines.push("");
      lines.push(`> **Suggestion**: ${issue.suggestion}`);
    }

    lines.push("");
    lines.push("---");
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Format review result into a GitHub comment body
 */
function formatReviewBody(result: ReviewResult, analysis: PRAnalysis, modelId: string): string {
  const lines: string[] = [];
  const { verdict, fpRate } = extractConsensusData(result);

  // Header
  lines.push("## 🤖 Dialectic PR Review");
  lines.push("");

  // Metrics — bullet list
  lines.push("### 📊 리뷰 메트릭");
  lines.push("");
  lines.push(`- **전략**: ${result.metadata.strategy.toUpperCase()} PR`);
  lines.push(`- **변경 파일**: ${result.metadata.filesReviewed}개`);
  lines.push(`- **변경 라인**: +${analysis.metrics.addedLines}/-${analysis.metrics.deletedLines}`);

  const areas = result.summary.affectedAreas.length > 0
    ? result.summary.affectedAreas.join(", ")
    : "기타";
  lines.push(`- **영향 영역**: ${areas}`);

  // Consensus line with verdict emoji
  const verdictEmoji = verdict === "APPROVE" ? "✅ LGTM" : verdict === "REQUEST_CHANGES" ? "🔴 Changes Requested" : "💬 Needs Discussion";
  lines.push(`- **Consensus**: ${verdictEmoji} (FP Rate: ${fpRate})`);

  // Flags
  const flagParts: string[] = [];
  if (analysis.context.flags.criticalModule) flagParts.push("🔴 크리티컬 모듈");
  if (analysis.context.flags.schemaChanged) flagParts.push("📐 스키마");
  if (analysis.context.flags.testChanged) flagParts.push("🧪 테스트 포함");
  if (analysis.context.flags.configOnly) flagParts.push("⚙️ 설정만");
  if (flagParts.length > 0) {
    lines.push(`- **플래그**: ${flagParts.join(", ")}`);
  }

  lines.push("");
  lines.push("---");
  lines.push("");

  // Debate narrative (STEP 1, 2, 3 including Executive Summary, Critical, Important, etc.) or fallback
  if (result.debateNarrative) {
    lines.push(result.debateNarrative);
  } else {
    lines.push(formatFallbackIssues(result));
  }

  lines.push("");
  lines.push("---");
  lines.push("");

  // Footer
  const modelName = formatModelName(modelId);
  lines.push(`*🪄 Generated by ${modelName} · [Dialectic PR Review](https://github.com/timenco/dialectic-pr)*`);
  lines.push("*💡 Tip: `skip-ai-review` 라벨을 추가하면 자동 리뷰를 건너뜁니다*");

  return lines.join("\n");
}

/**
 * Run a full PR review
 *
 * Shared orchestration logic used by both CLI and GitHub Action entry points.
 * Does NOT call process.exit() — callers are responsible for exit behavior.
 */
export async function runReview(options: ReviewOptions): Promise<ReviewOutput> {
  logger.section("Dialectic PR Review");

  // 1. Privacy Guard
  const privacyGuard = new PrivacyGuard();
  privacyGuard.displayDisclaimer();

  // 2. Load config
  const configLoader = new ConfigLoader();
  const repoPath = process.cwd();
  const config = await configLoader.load(repoPath, options.configPath);

  // 3. Adapters
  const claudeAdapter = new ClaudeAdapter(
    options.anthropicApiKey,
    config.model
  );
  const githubAdapter = new GitHubAdapter(options.githubToken);

  // 4. Core components
  const excludeFilter = new ExcludeFilter(config.exclude_patterns);
  const smartFilter = new SmartFilter();
  const frameworkDetector = new FrameworkDetector();
  const prAnalyzer = new PRAnalyzer(excludeFilter, smartFilter, frameworkDetector);
  const strategySelector = new StrategySelector();

  // 5. PR info
  const prInfo = {
    owner: options.owner,
    repo: options.repo,
    pullNumber: options.pullNumber,
    baseBranch: options.baseBranch,
    headBranch: "",
  };

  // 6. Fetch PR data
  logger.info("📥 Fetching PR data from GitHub...");
  const diff = await githubAdapter.getPRDiff(prInfo);
  const prFiles = await githubAdapter.getPRFiles(prInfo);

  // 7. Secrets validation
  privacyGuard.validateNoSecrets(diff);

  // 8. File transformation
  const changedFiles: ChangedFile[] = prFiles.map((f) => ({
    path: f.filename,
    content: f.patch || "",
    additions: f.additions,
    deletions: f.deletions,
  }));

  // 9. PR analysis
  const analysis = await prAnalyzer.analyze(diff, changedFiles, prInfo, repoPath);

  // 10. Strategy selection
  const strategy = strategySelector.select(analysis);

  // Skip strategy — post warning and return early
  if (strategy.name === "skip") {
    logger.warn("⚠️ PR is too large for meaningful review");
    const skipBody = `## 🤖 Dialectic PR Review\n\n⚠️ **PR Too Large**: This PR is too large for meaningful AI review (${(analysis.metrics.diffSize / 1024).toFixed(1)} KB).\n\nPlease split this into smaller PRs for better review quality.`;

    let posted = false;
    if (!options.dryRun) {
      await githubAdapter.postComment(prInfo, skipBody);
      posted = true;
    }

    return {
      issues: [],
      summary: {
        totalIssues: 0,
        criticalIssues: 0,
        affectedAreas: analysis.context.affectedAreas,
        overallAssessment: "PR too large for meaningful review",
      },
      metadata: {
        framework: analysis.context.framework,
        strategy: strategy.name,
        tokensUsed: 0,
        filesReviewed: 0,
        filesExcluded: analysis.excludedFiles.length,
        reviewDuration: 0,
      },
      commentBody: skipBody,
      posted,
    };
  }

  // 11. CLAUDE.md 자동 감지
  const conventions = await configLoader.loadClaudeMd(repoPath);

  // 11b. guardrails.json 자동 감지
  const guardrails = await configLoader.loadGuardrails(repoPath);

  // 11c. FP 패턴 조합 (builtin + framework - disabled + project)
  const rulesLoader = new ProjectRulesLoader();
  const basePatterns = rulesLoader.load(
    analysis.context.framework.name,
    guardrails.disabled_patterns || []
  );
  const allPatternsMap = new Map(basePatterns.map(p => [p.id, p]));
  for (const p of guardrails.patterns || []) {
    allPatternsMap.set(p.id, p); // 프로젝트 패턴이 빌트인 override
  }
  const allPatterns = Array.from(allPatternsMap.values());

  // 12. Consensus Engine — pass language
  const consensusEngine = new ConsensusEngine(
    claudeAdapter,
    conventions,
    config.language
  );
  const result = await consensusEngine.generateReview(
    analysis,
    strategy,
    allPatterns
  );

  // 13. Log results
  logger.section("Review Results");
  logger.info(`Total Issues: ${result.summary.totalIssues}`);
  logger.info(`Critical Issues: ${result.summary.criticalIssues}`);
  logger.info(`Assessment: ${result.summary.overallAssessment}`);

  // 14. Format and post
  const commentBody = formatReviewBody(result, analysis, config.model);
  let posted = false;

  if (!options.dryRun) {
    await githubAdapter.postComment(prInfo, commentBody);
    posted = true;
    logger.success(
      result.issues.length > 0
        ? "✅ Review posted to GitHub"
        : "✅ Review posted to GitHub (no issues found)"
    );
  } else {
    logger.info("🧪 Dry run mode - review not posted to GitHub");
  }

  return {
    issues: result.issues,
    summary: result.summary,
    metadata: result.metadata,
    commentBody,
    posted,
  };
}
