import { PRAnalysis, ReviewResult } from "./types.js";

/**
 * Convert model ID to display name
 * e.g. "claude-opus-4-6" → "Claude Opus 4.6"
 */
export function formatModelName(modelId: string): string {
  const match = modelId.match(/^claude-(\w+)-(\d+)-(\d+)/);
  if (match) {
    const [, family, major, minor] = match;
    return `Claude ${family.charAt(0).toUpperCase() + family.slice(1)} ${major}.${minor}`;
  }
  return modelId;
}

/**
 * Extract consensus verdict/fpRate for display in metrics
 */
export function extractConsensusData(result: ReviewResult): {
  verdict: string;
  fpRate: string;
} {
  let verdict = result.summary.verdict || "";
  const fpRate = result.summary.fpRate || "—";

  // Fallback inference if not provided
  if (!verdict) {
    if (result.summary.totalIssues === 0) verdict = "APPROVE";
    else verdict = "COMMENT";
  }

  return { verdict, fpRate };
}

/**
 * Format issues as a flat list (fallback when no debateNarrative)
 */
export function formatFallbackIssues(result: ReviewResult): string {
  const lines: string[] = [];

  if (result.issues.length === 0) {
    lines.push("### Review");
    lines.push("");
    lines.push(result.summary.overallAssessment);
    return lines.join("\n");
  }

  lines.push("### Issues");
  lines.push("");

  for (const issue of result.issues) {
    const emoji = {
      security: "🔐",
      bug: "🐛",
      performance: "⚡",
      maintainability: "🔧",
    }[issue.type];

    lines.push(`#### ${emoji} ${issue.title}`);
    lines.push("");
    lines.push(
      `**File**: \`${issue.file}\`${issue.line ? ` (Line ${issue.line})` : ""}`
    );
    lines.push(`**Type**: ${issue.type} | **Confidence**: ${issue.confidence}`);
    lines.push("");
    lines.push(issue.description);

    if (issue.suggestion) {
      lines.push("");
      lines.push(`> **Suggestion**: ${issue.suggestion}`);
    }

    lines.push("");
    lines.push("---");
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Format review result into a GitHub comment body
 */
export function formatReviewBody(result: ReviewResult, analysis: PRAnalysis, modelId: string): string {
  const lines: string[] = [];
  const { verdict, fpRate } = extractConsensusData(result);

  // Header
  lines.push("## 🤖 Dialectic PR Review");
  lines.push("");

  // Metrics — bullet list
  lines.push("### 📊 리뷰 메트릭");
  lines.push("");
  lines.push(`- **전략**: ${result.metadata.strategy.toUpperCase()} PR`);
  lines.push(`- **변경 파일**: ${result.metadata.filesReviewed}개`);
  lines.push(`- **변경 라인**: +${analysis.metrics.addedLines}/-${analysis.metrics.deletedLines}`);

  const areas = result.summary.affectedAreas.length > 0
    ? result.summary.affectedAreas.join(", ")
    : "기타";
  lines.push(`- **영향 영역**: ${areas}`);

  // Consensus line with verdict emoji
  const verdictEmoji = verdict === "APPROVE" ? "✅ LGTM" : verdict === "REQUEST_CHANGES" ? "🔴 Changes Requested" : "💬 Needs Discussion";
  lines.push(`- **Consensus**: ${verdictEmoji} (FP Rate: ${fpRate})`);

  // Flags
  const flagParts: string[] = [];
  if (analysis.context.flags.criticalModule) flagParts.push("🔴 크리티컬 모듈");
  if (analysis.context.flags.schemaChanged) flagParts.push("📐 스키마");
  if (analysis.context.flags.testChanged) flagParts.push("🧪 테스트 포함");
  if (analysis.context.flags.configOnly) flagParts.push("⚙️ 설정만");
  if (flagParts.length > 0) {
    lines.push(`- **플래그**: ${flagParts.join(", ")}`);
  }

  lines.push("");
  lines.push("---");
  lines.push("");

  // Debate narrative (STEP 1, 2, 3 including Executive Summary, Critical, Important, etc.) or fallback
  if (result.debateNarrative) {
    lines.push(result.debateNarrative);
  } else {
    lines.push(formatFallbackIssues(result));
  }

  lines.push("");
  lines.push("---");
  lines.push("");

  // Footer
  const modelName = formatModelName(modelId);
  lines.push(`*🪄 Generated by ${modelName} · [Dialectic PR Review](https://github.com/timenco/dialectic-pr)*`);
  lines.push("*💡 Tip: `skip-ai-review` 라벨을 추가하면 자동 리뷰를 건너뜁니다*");

  return lines.join("\n");
}
